### ISSUE TITLE
Documentation for self-hosting.

### ISSUE THREAD

**Issue by lgarron** [arturadib/strapdown#1]
Heeding the call for simplicity (but making sure that I could have control, on principle), I copied `strapdown.js` to my website and changed the URL. That didn't work, because it doesn't include the CSS files.

Presumably, I need to copy all (well, most of) the contents of https://github.com/arturadib/strapdown/tree/gh-pages/v/0.1 into a folder. Some instructions for that, as well as a concise download, would be nice.

**Comment by tjluoma** [comment]
Agreed. I tried to do the same thing, mostly to speed the loading of the page.

**Comment by arturadib** [comment]
Updated docs.

**Comment by lgarron** [comment]
Cool, I see it in 82f896ad5555ce2abdda1066740c8d10a37a3a41. That's just about the information I would have like to see  when I tried it out. G'luck with the project. :-)
