### ISSUE TITLE
header bug

### ISSUE THREAD

**Issue by yawnt** [arturadib/strapdown#2]
when i link an anchor in my markdown the header hides part of the text

example: http://yawnt.github.com/hater/documentation.html

nice job btw :D

**Comment by arturadib** [comment]
Not sure what's wrong with the output - this is what I see:

http://d.pr/i/6fhy

Can you send a screenshot of the problem? Thanks!

**Comment by yawnt** [comment]
sure...

this is how it appears when you click on `relationships` http://i.imgur.com/9odxm.jpg
this is how it should appear http://i.imgur.com/5KLnN.jpg (because the anchor is above `relationships`)

hope that made it clear, thanks again :)

**Comment by arturadib** [comment]
Ah, I see what you mean now.  That might require some tricky experiments with `src/strapdown.css` - the challenge will be making this work across devices. Leaving this open as a bug.

**Comment by yawnt** [comment]
thanks for taking the time to look into this :)
