### ISSUE TITLE
Serving Strapdown Files

### ISSUE THREAD

**Issue by jamiejackson** [arturadib/strapdown#28]
I usually open local files in a browser, and that works fine (xmp content is rendered). 

However, if I try to serve the file (it has an html extension) over Apache, I get the page and can view all the source I'd expect, but the rendered page is completely blank. If I inspect the request, I don't see the JS get requested by the browser at all.

Is there something I'm missing? I'm having a hard time understanding why I'm seeing this behavior.

**Comment by HowBowers** [comment]
I've noticed the same behavior serving from a IIS server, but only when the page is rendered in IE8 (IE10 works fine).

I added <head> and <body> tags into the HTML markup and then the page appeared as expected.

**Comment by jamiejackson** [comment]
I tried placing the strapdown code on an HTTPS server, and it works. So it was just an HTTP/HTTPS mismatch, and if I get an answer to #53, it will solve this problem.
