### ISSUE TITLE
xmp tag is depreciated

### ISSUE THREAD

**Issue by tjstebbing** [arturadib/strapdown#3]
Browsers may drop support for the behaviour provided by this tag.

**Comment by godDLL** [comment]
Not likely to happen. It is used in production all over the Interwebs. 
I wouldn't touch it.

**Comment by arturadib** [comment]
Yeah, plus I'm trying to get folks to reconsider this :)

https://www.w3.org/Bugs/Public/show_bug.cgi?id=12235#c15

(Mainly XML has CDATA, why can't HTML have something like it?)

**Comment by LostCrew** [comment]
hi arturadib,

i guess it should be good to have the markdown content inside a general-purpose tag like `<pre>` or `<div>`, and parse the content with strapdown only if the tag contains a specific attribute, for example a html5 friendly `data-markdown`.
the result would be:

```
<div data-markdown>
...
</div>
```

simple, clean and flexible enough.
how do you think about that?

thanks very much.

**Comment by arturadib** [comment]
We'd have to ask users to explicitly escape special HTML chars (like `<` and `>`). That'd be a pain, and that's the sole reason we're using `<xmp>`.

**Comment by billymoon** [comment]
Why not use either or... just let the developer decide which tehy want, and the script tries to load either way.
