### ISSUE TITLE
Any way for display Chinese?

### ISSUE THREAD

**Issue by strongme** [arturadib/strapdown#48]
As the titile goes, is there any way to solve the problem of Chines Displaying ? 
Thanks very much!

**Comment by guneysus** [comment]
Same problem for Turkish unicode chars. Following.

**Comment by cslecours** [comment]
You need to add `<meta charset="utf-8">` between the `<head>` and `</head>` blocks.

**Comment by dotku** [comment]
@strongme it supports Chinese charaters. Checkout here: http://dotku.github.io/cn/tech/javascript/strapdown.js/
