### ISSUE TITLE
Any chance that multimarkdown could be supported?

### ISSUE THREAD

**Issue by tjluoma** [arturadib/strapdown#5]
Markdown is great, but I like the tables and footnotes support added by [MultiMarkdown](http://fletcherpenney.net/multimarkdown/).

Any chance strapdown could support MultiMarkdown instead of just plain Markdown?

_(Please note: I have no idea how simple or complex such a change would be, hence the question.)_

**Comment by arturadib** [comment]
The best Markdown JS lib I've found is https://github.com/chjj/marked and I don't think they support MultiMarkdown. It's a matter of finding a good JS lib that supports Github-style AND Multi... not so easy.
