### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by stdg11** [arturadib/strapdown#58]
Is it possible to use this with SSL enabled, without having to load insecure content?

I cannot resolve https://strapdownjs.com/v/0.2/strapdown.js

If I try with https://raw.githubusercontent.com/arturadib/strapdown/gh-pages/v/0.2/strapdown.js it loads without a theme.

**Comment by joedf** [comment]
Either, self host or modify strapdown.js to match the new paths.
