### ISSUE TITLE
https://strapdownjs.com has a wrong certificate

### ISSUE THREAD

**Issue by orecht** [arturadib/strapdown#92]
Browsing to https://strapdownjs.com give the folowing error in Firefox:

strapdownjs.com uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

Could you check your github pages configuration?

**Comment by lazyval** [comment]
@arturadib recently Github guys made it way easier to fix: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Can you please go and update `A` record? (hopefully you would not need to fix all the css and img files as well). Unfortunately, it's ain't something we can contribute ourselves.

At current state broken certificate prevents some of the sites from using strapdown.js properly. Because javascript is served from `strapdownjs.com`, when browser loads https page that uses strapdown, script is blocked as the mixed content.

**Comment by arturadib** [comment]
i've made the A record changes, it needs to propagate though.. fingers
crossed.
-Artur

**Comment by walterdavis** [comment]
I looked yesterday to see if Strapdown was at CDNJS, and there was an issue (closed) saying that they had asked, but nobody replied. While it's great that you are willing to host it yourself, and to keep the DNS set correctly, maybe letting meadows bloom (by letting it be on all the public CDNs) would lighten the load.

Just a thought,

Walter

**Comment by lazyval** [comment]
@walterdavis as far as I understand, github has it's own CDN for github pages and this is what Arthur is using to host strapdown. How is that compares to CDNJS (I am not a frontend dev per se)?

**Comment by lazyval** [comment]
So I wrote to github support, and they've expedited certificate creation and now https mode is on! 

<img width="426" alt="screenshot 2018-10-22 18-14-43" src="https://user-images.githubusercontent.com/235297/47300930-5a7c5880-d626-11e8-9d08-f6a0d8071647.png">

Horaaay! Thanks to @arturadib and Thomas Baillie from github support

<img width="549" alt="re https support for a site with custom domain name - johnysilver7 gmail com - gmail 2018-10-22 18-16-43" src="https://user-images.githubusercontent.com/235297/47301032-a202e480-d626-11e8-9c63-dea50f131819.png">

**Comment by walterdavis** [comment]
CDNJS is a semi-complete collection of front-end software, all of it available elsewhere, which provides diversity and redundancy, at the cost of maybe needing to update your libraries in more than one place. I have put a few libraries there that were abandoned by their creators. I don't know what their policy is about posting maintained software -- who does the updating when a new version comes out? The physical way that it works is you clone the CDNJS repo, make an addition, and send the maintainers a pull request. It usually goes through quickly and automatically if you are already validated. It was years ago that I was validated, though, so who knows what the process is like now.

Walter
