### ISSUE TITLE
Emoji Support?

### ISSUE THREAD

**Issue by tnb24** [arturadib/strapdown#96]
title. Can the devs please add emoji support as everyone uses emojis right now

**Comment by fu-sen** [comment]
If you load Strapdown.js and put the emoji code in Unicode, it can be displayed.
For example, if you enter `:)` and want to display `😃`, you need a separate library.

**Comment by tnb24** [comment]
Thanks! I used the unicode and it worked

**Comment by fu-sen** [comment]
I am glad to help you. 😄 I'm Japanese, so I enter emoji directly. 🎈

If you're curious about the age of the Bootstrap / Bootswatch themes, check here. I fork to reflect the latest version.
https://github.com/fu-sen/strapdown
